# Generated by Django 3.0.2 on 2021-08-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_credit_enabled', models.BooleanField(default=False)),
                ('extra_credit_percentage', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='storetransaction',
            name='currency',
            field=models.CharField(choices=[('ADA', 'Ada'), ('BTC', 'Btc'), ('ETH', 'Eth'), ('XRP', 'Xrp'), ('XMR', 'Xmr'), ('BNB', 'Bnb'), ('LTC', 'Ltc'), ('DOGE', 'Doge'), ('USDT.ERC20', 'Usdt')], max_length=255),
        ),
    ]
